export const heroWords = [
  "IT infrastructure partner",
  "hardware supplier",
  "certified cabling crew",
  "printer maintenance team",
  "systems integrator",
];

export const bigWords = [
  "reliable.",
  "ready in 24h.",
  "engineered properly.",
  "fully supported.",
];

export const brands = [
  "HP",
  "Cisco",
  "Dell",
  "Huawei",
  "Toshiba",
  "Microsoft",
  "Lenovo",
  "Kyocera",
  "Canon",
  "Samsung",
  "Western Digital",
  "Logitech",
];

export const categories = [
  {
    id: "furniture",
    title: "Office Furniture",
    sub: "ergonomic desks, executive chairs, storage",
    img: "/images/products/desk.jpg",
    count: "45+ items",
  },
  {
    id: "computers",
    title: "Computers & Laptops",
    sub: "business notebooks, workstations, docks",
    img: "/images/products/laptop.jpg",
    count: "60+ items",
  },
  {
    id: "printing",
    title: "Printers & Copiers",
    sub: "multifunction machines, toner, OEM kits",
    img: "/images/products/copier.jpg",
    count: "30+ models",
  },
  {
    id: "networking",
    title: "Networking & Switching",
    sub: "Cisco, Huawei, rack switches, routers",
    img: "/images/products/switch.jpg",
    count: "50+ items",
  },
  {
    id: "cables",
    title: "Cabling & Fiber",
    sub: "Cat-6A, Cat-7, patch leads, reels",
    img: "/images/products/cable.jpg",
    count: "80+ variants",
  },
  {
    id: "accessories",
    title: "Computer Accessories",
    sub: "ergonomic keyboards, mice, webcams",
    img: "/images/products/keyboard.jpg",
    count: "110+ items",
  },
  {
    id: "storage",
    title: "Storage & Media",
    sub: "encrypted SSDs, external HDDs, flash drives",
    img: "/images/products/harddrive.jpg",
    count: "40+ items",
  },
  {
    id: "presentation",
    title: "Conference & Whiteboards",
    sub: "magnetic boards, projectors, mobile stands",
    img: "/images/products/whiteboard.jpg",
    count: "25+ items",
  },
];

export const products = [
  {
    id: 1,
    name: "Dell Inspiron Business Laptop",
    brand: "Dell",
    spec: "Intel Core i7 · 16GB DDR4 · 512GB NVMe SSD · Windows 11 Pro",
    fullDesc: "Engineered for demanding office workflows, remote management, and rock-solid daily reliability. Pre-configured and tested by Eykotech technicians before dispatch.",
    img: "/images/products/laptop.jpg",
    cat: "computers",
    tag: "In stock",
    priceGuidance: "$749,00",
    inStockCount: 14,
    rating: 4.9,
    warranty: "3 Years On-site Exchange",
    features: [
      "15.6\" Full HD Anti-Glare IPS display",
      "Full port suite: HDMI, RJ-45 Gigabit LAN, USB-C",
      "Hardware TPM 2.0 security chip",
      "Backlit spill-resistant German layout keyboard",
    ],
  },
  {
    id: 2,
    name: "Toshiba e-STUDIO High-Yield MFP",
    brand: "Toshiba",
    spec: "Digital heavy-duty copier · 28 CPM · up to 90,000 pages/month",
    fullDesc: "Workhorse multifunction system for busy offices and law firms. Includes automatic document feeder, duplex printing, and network scan-to-folder.",
    img: "/images/products/copier.jpg",
    cat: "printing",
    tag: "Popular",
    priceGuidance: "$1.420,00",
    inStockCount: 6,
    rating: 4.8,
    warranty: "Includes 24h maintenance SLA",
    features: [
      "Scan-to-email and SMB network folders directly",
      "Dual 550-sheet paper cassettes + bypass tray",
      "Heavy duty ceramic drum designed for 100k+ impressions",
      "Quiet operation mode suitable for open offices",
    ],
  },
  {
    id: 3,
    name: "Cisco Catalyst 2960 Managed Switch",
    brand: "Cisco",
    spec: "24-Port 10/100/1000 Gigabit · 2 Dual-rate SFP uplinks · Layer 2+",
    fullDesc: "Enterprise-grade wired connectivity with advanced QoS, 802.1Q VLAN support, and hardware-level packet inspection for business networks.",
    img: "/images/products/switch.jpg",
    cat: "networking",
    tag: "Popular",
    priceGuidance: "$385,00",
    inStockCount: 18,
    rating: 5.0,
    warranty: "Cisco Limited Lifetime",
    features: [
      "Layer 2 switching with static routing and ACLs",
      "Energy Efficient Ethernet (IEEE 802.3az)",
      "Cisco Auto SmartPorts for instant IP phone setup",
      "Silent fanless operation on select sub-models",
    ],
  },
  {
    id: 4,
    name: "Enterprise High-Speed External HDD",
    brand: "Western Digital",
    spec: "4TB to 18TB · USB 3.2 Gen 2 · Hardware 256-bit AES Encryption",
    fullDesc: "Reliable automated backup destination for office workstations and NAS mirrors. Ruggedized housing with active shock absorption.",
    img: "/images/products/harddrive.jpg",
    cat: "storage",
    tag: "In stock",
    priceGuidance: "$119,00",
    inStockCount: 42,
    rating: 4.7,
    warranty: "5 Years Manufacturer",
    features: [
      "Hardware-level AES 256-bit password protection",
      "Optimized for 24/7 continuous backup rotations",
      "Includes both USB-A and USB-C connection cables",
      "Vibration-damping rubber feet for desk stability",
    ],
  },
  {
    id: 5,
    name: "High-Speed Encrypted Flash Drives",
    brand: "SanDisk / Kingston",
    spec: "64GB to 512GB · 400 MB/s Read · Waterproof metal casing",
    fullDesc: "Pocket-sized rugged flash drives for safe technician deployment, ISO booting, and fast transfer of bulky CAD or database archives.",
    img: "/images/products/pendrive.jpg",
    cat: "storage",
    tag: "In stock",
    priceGuidance: "$22,50",
    inStockCount: 120,
    rating: 4.8,
    warranty: "5 Years Replacement",
    features: [
      "Solid zinc alloy unibody construction",
      "Backward compatible with USB 3.0 and USB 2.0",
      "RescuePRO Deluxe recovery software license included",
      "Convenient keyring loop for IT field technicians",
    ],
  },
  {
    id: 6,
    name: "Ergonomic Dual-Motor Sit-Stand Desk",
    brand: "Eykotech ProWork",
    spec: "160x80cm Oak/White · Dual Motors · Anti-collision sensor · Memory controller",
    fullDesc: "Premium commercial-grade sit-stand desk. Sturdy three-stage steel lifting columns deliver whisper-quiet height adjustment from 62cm to 128cm.",
    img: "/images/products/desk.jpg",
    cat: "furniture",
    tag: "New",
    priceGuidance: "$480,00",
    inStockCount: 15,
    rating: 4.9,
    warranty: "7 Years Frame & Motors",
    features: [
      "Dual German-engineered motors (<45dB sound level)",
      "Digital handset with 4 custom height presets",
      "Integrated cable management tray and grommet pass-throughs",
      "125 kg safe working load capacity",
    ],
  },
  {
    id: 7,
    name: "Armoured Technician Laptop Backpack",
    brand: "Targus / Eykotech",
    spec: "Fits up to 17.3\" laptops · Water-repellent ballistic nylon · Cable organizer",
    fullDesc: "Designed specifically for IT administrators and field engineers needing to transport laptops, console cables, crimpers, and testers securely.",
    img: "/images/products/laptopbag.jpg",
    cat: "accessories",
    tag: "Popular",
    priceGuidance: "$69,00",
    inStockCount: 28,
    rating: 4.8,
    warranty: "Lifetime Warranty",
    features: [
      "Shock-absorbing SafePort sling suspension cradle",
      "Dedicated tool and cable pouch compartments",
      "Trolley pass-through strap for travel",
      "Reinforced weatherproof base panel",
    ],
  },
  {
    id: 8,
    name: "Full HD 1080p Business Conference Cam",
    brand: "Logitech Pro",
    spec: "1080p @ 60fps · Dual Noise-Canceling Microphones · Privacy Shutter",
    fullDesc: "Crystal-clear optics for Microsoft Teams, Zoom, and boardroom conferences. Auto-light correction ensures crisp skin tones in uneven office light.",
    img: "/images/products/camera.jpg",
    cat: "accessories",
    tag: "New",
    priceGuidance: "$89,00",
    inStockCount: 35,
    rating: 4.9,
    warranty: "2 Years Replacement",
    features: [
      "RightLight 2 automatic low-light optimization",
      "90-degree wide field of view with auto-framing",
      "Physical privacy sliding lens shutter",
      "Plug & play USB compatibility, no drivers required",
    ],
  },
  {
    id: 9,
    name: "Executive Ergonomic Synchron Mesh Chair",
    brand: "Eykotech ErgoLine",
    spec: "Breathable mesh back · Dynamic lumbar support · 4D adjustable armrests",
    fullDesc: "Approved for 8+ hour continuous seated work. Synchronous mechanism adapts tilt tension to user body weight for pressure-free circulation.",
    img: "/images/products/chair.jpg",
    cat: "furniture",
    tag: "In stock",
    priceGuidance: "$329,00",
    inStockCount: 22,
    rating: 5.0,
    warranty: "5 Years Full Cover",
    features: [
      "Weight-sensitive synchronous reclining system",
      "4D armrests with width, depth, height and angle adjust",
      "Breathable high-tensile mesh resistant to sagging",
      "Bifma and TÜV Rheinland certified safety gas lift",
    ],
  },
  {
    id: 10,
    name: "Cat-6A LSZH Shielded Patch & Bulk Cables",
    brand: "Eykotech Cables",
    spec: "10 Gbps @ 500 MHz · S/FTP Double Shielded · Low Smoke Zero Halogen",
    fullDesc: "Certified for 10-Gigabit Ethernet runs, PoE+ (802.3at) security cameras, and high-density rack patching. Available in pre-terminated lengths or 305m drums.",
    img: "/images/products/cable.jpg",
    cat: "cables",
    tag: "Popular",
    priceGuidance: "$4,20 / 305m drum $135",
    inStockCount: 400,
    rating: 4.9,
    warranty: "25 Year Channel Guarantee",
    features: [
      "100% bare copper conductors (26 AWG / 23 AWG)",
      "Molded snagless boots with gold-plated 50u contacts",
      "LSZH sheath compliant with European fire safety standards",
      "Individually Fluke-tested and certified",
    ],
  },
  {
    id: 11,
    name: "Wireless Multi-Device Keyboard & Mouse Set",
    brand: "Logitech Business",
    spec: "Dual Bluetooth & 2.4GHz USB · 3-Device Pairing · 36-Month Battery Life",
    fullDesc: "Whisper-quiet scissor switches paired with an ergonomic contoured laser mouse. Seamlessly toggle between workstation, laptop, and tablet with one key.",
    img: "/images/products/keyboard.jpg",
    cat: "accessories",
    tag: "In stock",
    priceGuidance: "$64,90",
    inStockCount: 45,
    rating: 4.8,
    warranty: "3 Years Exchange",
    features: [
      "Cushioned palm rest and curved keycap layout",
      "Cross-computer copy-paste via Flow technology",
      "Encryption: AES 128-bit wireless security",
      "Laser mouse tracks accurately even on glass surfaces",
    ],
  },
  {
    id: 12,
    name: "Magnetic Porcelain Enamelled Whiteboard",
    brand: "Nobo / Eykotech",
    spec: "180x120cm · Scratch-Resistant Ceramic Surface · Anodized Aluminium Frame",
    fullDesc: "High-use whiteboard built for project war rooms, meeting hubs, and engineering brainstorms. High-density magnetic ceramic prevents ghosting forever.",
    img: "/images/products/whiteboard.jpg",
    cat: "presentation",
    tag: "New",
    priceGuidance: "$165,00",
    inStockCount: 12,
    rating: 4.9,
    warranty: "25 Year Surface Guarantee",
    features: [
      "Zero ghosting or staining even after dry marker leaves for months",
      "Full-length aluminium clip-on marker tray",
      "Corner mounting kit with neat concealment caps",
      "Super-magnetic backplate holds heavy documents securely",
    ],
  },
];

export const filters = [
  "all",
  "computers",
  "printing",
  "networking",
  "storage",
  "furniture",
  "cables",
  "accessories",
  "presentation",
];

export const detailedServices = [
  {
    id: "cabling",
    title: "Structured Cabling & High-Speed Fiber",
    subtitle: "Clean trunking, certified 10G patch fields, and rock-solid backbone links.",
    tag: "Core Specialty",
    icon: "cabling",
    summary: "From a 10-desk office move to full multi-story campus cabling, we install, label, and certify every port according to ISO/IEC 11801 standards.",
    highlights: [
      "Cat-6A & Cat-7 S/FTP copper terminations with Fluke certification",
      "Single-mode (OS2) and Multi-mode (OM4) optical fiber splices",
      "Patch rack reorganization, color-coded cable dressing, and port audit",
      "Floor-box installations, skirting trunking, and ceiling access points",
    ],
    sla: "On-site survey within 24h in Braunschweig area",
    metric: "10,000+ certified drops installed",
    img: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1200&auto=format&fit=crop",
    imgAlt: "Patch field dressed and labelled in a customer rack",
    cta: "Book a site survey",
    cat: "cables",
    catLabel: "cabling stock",
    stats: [
      { label: "Certified drops", value: "10,000", unit: "+" },
      { label: "On-site survey", value: "24", unit: "h" },
    ],
  },
  {
    id: "networking",
    title: "Enterprise Cisco & Huawei Systems",
    subtitle: "Secure routers, managed core switches, firewalls & site-to-site VPNs.",
    tag: "Certified Engineers",
    icon: "network",
    summary: "We design resilient network architectures that keep VoIP clear, customer databases secure, and employee Wi-Fi blazing across every corner of your office.",
    highlights: [
      "Cisco Catalyst 2960 / 9000 & Huawei NE / AR router deployments",
      "VLAN partitioning for guest networks, IoT, and sensitive accounting",
      "Hardware firewall implementation & multi-WAN failover configs",
      "High-density Wi-Fi 6 heatmapping and controller installation",
    ],
    sla: "Emergency dispatch < 4h for managed network clients",
    metric: "99.99% uptime target",
    img: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
    imgAlt: "Server and switch stack kept available for a client",
    cta: "Talk to an engineer",
    cat: "networking",
    catLabel: "networking stock",
    stats: [
      { label: "Uptime target", value: "99.99", unit: "%" },
      { label: "Emergency dispatch", value: "<4", unit: "h" },
    ],
  },
  {
    id: "printers",
    title: "Printers, Copiers & Fleet Maintenance",
    subtitle: "Turnkey equipment leasing, genuine parts, and proactive maintenance.",
    tag: "HP & Toshiba Partner",
    icon: "printer",
    summary: "Stop fighting paper jams and expensive toner emergencies. We supply workhorse multifunction machines, automate toner re-orders, and fix issues before you notice.",
    highlights: [
      "Full HP LaserJet, Enterprise MFP & Toshiba e-STUDIO leasing",
      "Original manufacturer fuser units, transfer belts, and roller kits",
      "On-site diagnostic repair by factory-trained technicians",
      "Transparent per-page managed print contracts with zero hidden fees",
    ],
    sla: "Next-business-day swap if machine cannot be fixed on-site",
    metric: "450+ managed printers active",
    img: "/images/products/copier.jpg",
    imgAlt: "Multifunction copier in daily use at a client office",
    cta: "Service my fleet",
    cat: "printing",
    catLabel: "printers and copiers",
    stats: [
      { label: "Managed printers", value: "450", unit: "+" },
      { label: "Machine swap", value: "Next", unit: "business day" },
    ],
  },
  // {
  //   id: "furniture",
  //   title: "Workstation Ergonomics & Complete Fitouts",
  //   subtitle: "Height-adjustable desks, ergonomic seating, and complete floor deliveries.",
  //   tag: "Turnkey Logistics",
  //   icon: "desk",
  //   summary: "Equip your team with desks, monitor arms, and chairs they love coming into the office for. Delivered by our own fleet and assembled ready for immediate work.",
  //   highlights: [
  //     "Commercial dual-motor sit-stand desks with clean under-desk wire looms",
  //     "TÜV-certified ergonomic task chairs with adjustable lumbar contours",
  //     "Acoustic desk partition screens and sound-dampening meeting pods",
  //     "Full office relocations, assembly, and old furniture recycling",
  //   ],
  //   sla: "Flexible weekend / after-hours installation to prevent downtime",
  //   metric: "2,500+ desks delivered & built",
  //   img: "/images/products/desk.jpg",
  //   imgAlt: "Height-adjustable desk set up and cable-managed",
  //   cta: "Plan a fitout",
  //   cat: "furniture",
  //   catLabel: "desks and seating",
  //   stats: [
  //     { label: "Desks delivered", value: "2,500", unit: "+" },
  //     { label: "Installation slots", value: "Weekends", unit: "" },
  //   ],
  // },
];

export const services = [
  "Huawei routing: NE40E/80E, PTN 1900/912, mid-range LAN/WAN",
  "Cisco Catalyst access, distribution & core, ASA firewalls, IOS updates",
  "Windows & Linux (SUSE) server administration, Exchange",
  "Wireless builds, VoIP & VPN rollouts",
  "Structured cabling and full network design",
  "Web hosting, design & software development",
];

export const jobs = [
  {
    n: "01",
    title: "Auto-Showroom re-cabled with OM4 optical fiber",
    location: "Braunschweig North",
    note: "48 Cat-6A endpoints + 10G optical link dressed cleanly per rack row",
    status: "done",
    date: "This week",
  },
  {
    n: "02",
    title: "Medical practice copier maintenance & fuser kit overhaul",
    location: "Braunschweig City Center",
    note: "HP Color LaserJet Enterprise serviced on-site within 3 hours",
    status: "done",
    date: "Yesterday",
  },
  {
    n: "03",
    title: "Logistics HQ 48-port Cisco core switch migration & VLAN partition",
    location: "Braunschweig Harbour District",
    note: "Zero-downtime cutover scheduled with redundant link validation",
    status: "ongoing",
    date: "In progress",
  },
  {
    n: "04",
    title: "35 Motorized sit-stand desks floor rollout & cable looms",
    location: "Wolfsburg Corridor",
    note: "3 floors, staged early delivery, completely installed and ready for Monday",
    status: "scheduled",
    date: "Scheduled",
  },
];

export const testimonials = [
  {
    quote:
      "They re-cabled our entire ground floor over a single weekend and Monday morning every single workstation connected instantly without a single glitch. Remarkable execution.",
    name: "Katrin S.",
    role: "Head of Logistics & Operations",
    company: "NordLogistics GmbH · Braunschweig",
    rating: 5,
    verified: true,
  },
  {
    quote:
      "We source all our sit-stand desks, laser toner, and Cisco access switches from Eykotech now. Having one local phone number for procurement, setup, and emergency fixes saves us countless hours.",
    name: "Jonas M.",
    role: "IT Administrator & Facility Lead",
    company: "BMA Engineering · Braunschweig",
    rating: 5,
    verified: true,
  },
  {
    quote:
      "When our main office copier failed right before a critical tax filing, their technician was in our office within 90 minutes with original HP replacement rollers. Outstanding local commitment.",
    name: "Petra L.",
    role: "Senior Partner & Practice Manager",
    company: "Kanzlei Dr. Linden & Partner · Braunschweig",
    rating: 5,
    verified: true,
  },
];

export const faqs = [
  {
    q: "Do you only sell the boxes, or can you install and configure everything?",
    a: "Installation is our core strength. Whether you need 40 sit-stand desks built and cable-routed, a 48-port Cisco switch configured with isolated VLANs, or a multi-room fiber backbone spliced and certified, we deliver, install, test, and hand over turnkey systems.",
    category: "services",
  },
  {
    q: "Which network and computer brands do you officially support?",
    a: "We actively stock and service equipment from Cisco, HP, Dell, Huawei, Toshiba, Microsoft, Lenovo, Kyocera, and Canon. Our workshop is equipped with specialized diagnostic gear and authentic OEM components.",
    category: "support",
  },
  {
    q: "How quickly can you get to us if something breaks?",
    a: "Managed network clients get emergency dispatch inside four hours. For printers and copiers we aim to fix on site, and if a machine cannot be repaired the same visit we swap it the next business day. Everyone else gets an on-site survey within 24 hours in the Braunschweig area.",
    category: "support",
  },
  {
    q: "Do you deliver, and how far do you go?",
    a: "We run our own fleet rather than relying on couriers, so we deliver across Braunschweig and the surrounding region, typically within 24 to 48 hours. Larger fitouts can be staged over a weekend or after hours so your team never loses a working day.",
    category: "delivery",
  },
  {
    q: "What does a quote cost, and how do I get one?",
    a: "Quotes are free and carry no obligation. Call or email us with what you need, or bring the equipment into the showroom on Hamburger Strasse. For repairs we tell you honestly when a fix is not worth the money and a replacement makes more sense.",
    category: "sales",
  },
  {
    q: "Can we set up an ongoing maintenance contract?",
    a: "Yes. Contracts cover priority response, scheduled service visits, monitoring, and discounted parts at a predictable monthly price. Managed print contracts are billed per page with no hidden fees, and toner re-orders are automated so you do not run dry.",
    category: "services",
  },
  {
    q: "Do you work with businesses that already have their own IT team?",
    a: "Often. Plenty of our clients have internal IT and use us for the hands-on work: structured cabling, rack tidies, hardware supply, printer fleets, and overflow installation capacity. We document everything we configure and hand it over cleanly.",
    category: "services",
  },
];

export const footerShop = [
  ["Office Furniture & Desks", "furniture"],
  ["Computers & Laptops", "computers"],
  ["Printers & Copiers", "printing"],
  ["Networking & Cisco", "networking"],
  ["Structured Cabling", "cables"],
  ["Storage & Backup Media", "storage"],
  ["Accessories & Peripherals", "accessories"],
];

export const footerCompany = [
  ["About Eykotech", "about"],
  ["Delivery Fleet & Coverage", "delivery"],
  ["Repairs & Maintenance", "repairs"],
  ["FAQ", "faq"],
  ["Contact & Showroom", "contact"],
];

export const specialities = [
  { group: "Networking & Switching", items: ["Huawei NE40/80E · PTN1900/912 · low- and mid-range routers", "Cisco Catalyst access, distribution and core switches, routers, IOS updates"] },
  { group: "Systems & Servers", items: ["MS Windows Server, Exchange server, Linux SUSE administration", "VoIP and VPN network solutions"] },
  { group: "Design & Build", items: ["Network cabling and network design", "Web hosting", "Web design & software development"] },
];

export const address = {
  street: "Hamburger Strasse 73",
  city: "38122 Braunschweig, Germany",
  email: "info@eykotech.com",
  hours: "Mon–Fri · 08:00AM–05:00PM",
};